name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }}
        env:
          DOCKER_CLI_ACI_USERNAME: ${{ github.actor }}
          DOCKER_CLI_ACI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
